{% set name = "jupyterlab_genv" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_genv-{{ version }}.tar.gz
  sha256: 9db811955c8d23bc404adf0840275c083d97913be19c965e9f4a3c6d2ae7a3f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.3.1
    - jupyterlab ~=3.1
    - hatch-jupyter-builder >=0.5
  run:
    - python >=3.7
    - jupyter_server <2,>=1.6
    - genv

test:
  imports:
    - jupyterlab_genv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyterlab-genv/
  summary: A JupyterLab extension for managing GPU environments using genv.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - omer-dayan
    - razrotenberg
